services:
  # database
  postgres:
    image: postgres:18.3-alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: my_stock
      POSTGRES_USER: kev
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kev -d my_stock"] # check if postgres is fully setup & ready to accept connections
      interval: 5s # retry db check every 5 seconds until its ready
      timeout: 5s # if one db check fails, retry again in 5 seconds
      retries: 5 # retry db check 5 times; if all 5 fail to connect deem db unhealthy
    volumes:
      - my_stock:/var/lib/postgresql
    secrets:
      - db_passwd

  # api
  python_api:
    depends_on:
      postgres:
        condition: service_healthy # wait for postgres db to be fully setup & ready to accept connections
    build: ./
    ports:
      - "8000:8000"
    secrets:
      - db_passwd

secrets:
  db_passwd:
    file: secrets/password.txt

volumes:
  my_stock:
