name: CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  create_ec2_and_run_docker_multicontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v6.0.2

      - name: Download Terraform CLI in runner
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        id: tf_apply_step
        run: |
          terraform apply -auto-approve
          echo "instance_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      - name: EC2 SSH Login
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ steps.tf_apply_step.outputs.instance_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script_path: ./run-docker-app.sh

# Todo: Deploy image to run in AWS => create a 'automated-cd.yaml' workflow
# 1. IAC: run Terraform action to build ec2 instance:
#  use 'user_data'; on first ec2 boot install docker
# upload ec2 ssh login e.g. ssh -i .pem user@ip_address
# 2. ssh into ec2:
# docker pull image
# docker compose up -d
