name: Code linting and Unit tests
on:
  push:
    branches: [main] # code pushed to main branch only
  pull_request:
    branches: [main] # PR merging to main branch only
jobs:
  check_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install Python 3.13
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Run ruff-action Python linter
        uses: astral-sh/ruff-action@v3.6.1

  unit_tests:
    needs: check_linting # if linting checks don't pass, dont run tests
    runs-on: ubuntu-latest
    steps:
      - name: Download repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install Python 3.13
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Install project dependencies
        run: pip install fastapi uvicorn sqlalchemy psycopg2-binary pytest httpx

      - name: Run unit tests
        run: pytest

  docker_and_trivy:
    needs: unit_tests # if unit tests fail dont build docker image or scan it with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download repo to runner
        uses: actions/checkout@v6.0.2

      - name: Docker Hub login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image # docker is already preinstalled in runner
        run: docker build -t rocketman02/python-fastapi-postgres:${{ github.sha }} .

      - name: Trivy report (docker image)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: "rocketman02/python-fastapi-postgres:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

      - name: Trivy security scan (docker image)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: "rocketman02/python-fastapi-postgres:${{ github.sha }}"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          exit-code: "1"

      - name: Push Docker image to Docker Hub # only if Trivy security scan passed
        run: docker push rocketman02/python-fastapi-postgres:${{ github.sha }}

# Todo: Deploy image to run in AWS
