name: CICD Pipeline
on:
  pull_request:
    branches: [ main ]
env:
  MY_DOCKER_IMAGE: rocketman02/python-fastapi-postgres:${{ github.sha }}
jobs:
  check_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install Python 3.13
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Run ruff-action Python linter
        uses: astral-sh/ruff-action@v3.6.1

  unit_tests:
    needs: check_linting # if linting checks don't pass, dont run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install Python 3.13
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Install project dependencies
        run: pip install fastapi uvicorn sqlalchemy psycopg2-binary pytest httpx

      - name: Run unit tests
        run: pytest

  docker_and_trivy:
    needs: unit_tests # if unit tests fail dont build docker image or scan it with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v6.0.2

      - name: Docker Hub login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image # docker is already preinstalled in runner
        run: docker build -t $MY_DOCKER_IMAGE .

      - name: Trivy report (docker image)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: "${{ env.MY_DOCKER_IMAGE }}"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

      - name: Trivy security scan (docker image)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: "${{ env.MY_DOCKER_IMAGE }}"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          exit-code: "1"

      - name: Push Docker image to Docker Hub # only if Trivy security scan passed
        run: docker push ${{ env.MY_DOCKER_IMAGE }}

  create_ec2_and_run_docker_app:
    needs: docker_and_trivy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v6.0.2

      - name: Download Terraform CLI in runner
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        id: tf_apply_step
        run: |
          terraform apply -auto-approve
          echo "instance_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      - name: Wait 3 minutes for EC2 to be ready for SSHing
        run: |
          echo "Waiting for EC2 to fully start up to accept SSH connections..."
          sleep 180

      - name: SSH into EC2 and pull & run docker app
        uses: appleboy/ssh-action@v1.2.5
        env:
          MY_POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
        with:
          host: ${{ steps.tf_apply_step.outputs.instance_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script_path: ./run-docker-app.sh
